# -*- coding: utf-8 -*-
"""ImageChat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-qb52NbOnjB6jlUfHUWjqiuIJG1_-6OM

# **Install Required Libraries**
"""

!pip install google-generativeai grpcio grpcio-tools gradio

"""# **Run Gradio App**"""

# build gradio frontend
import google.generativeai as genai
import gradio as gr
import numpy as np
import PIL.Image

genai.configure(api_key="input your Google AI Studio API key")

def ImageChat(image, prompt):

  # load model
  model = genai.GenerativeModel("gemini-pro-vision")

  # check image file and convert to a Numpy array
  if isinstance(image, np.ndarray):

        img = PIL.Image.fromarray(image)
  else:
        img = PIL.Image.open(image)

  response =  model.generate_content([prompt, img])

  return response.text


app = gr.Interface(ImageChat,
                   inputs = [gr.Image(), gr.Text()],
                   outputs = gr.Text(),
                   title = "Image Chat",
                   theme = gr.themes.Soft())

app.launch(debug = True)